### ISSUE TITLE
CSVs are uploaded to different subdirectories, so flatten-tool doesn't pick any of them up

### ISSUE THREAD

**Issue by Bjwebb** [Open-Telecoms-Data/cove-ofds#100]
e.g. https://ofds.cove.opendataservices.coop/data/144ba0c0-1f41-47b9-a981-ebe0402ee7e6

CSVs are in:
https://ofds.cove.opendataservices.coop/media/144ba0c0-1f41-47b9-a981-ebe0402ee7e6/supplied_data/ff4379c9-2a97-4cb0-badd-9e0bb76a3016/tmp.csv
https://ofds.cove.opendataservices.coop/media/144ba0c0-1f41-47b9-a981-ebe0402ee7e6/supplied_data/0c25437b-90bd-4f98-9d49-32e9ad578888/nodes.csv

But, flatten-tool is only looking directly under /media/144ba0c0-1f41-47b9-a981-ebe0402ee7e6/supplied_data/

One approach would be to just remove the subdirectories https://github.com/Open-Telecoms-Data/cove-ofds/commit/dd7e6cc281c8d8dcdec81772f2c4327790ce8c7e, but I'm assuming they're there for a reason.

**Comment by ghost** [comment]
> I'm assuming they're there for a reason.

Yes, it's to meet several requirements - make sure that someone downloading gets original file name, make sure the same filename can be uploaded twice without overloading.

This also explains how this bug crept in; CSV uploading was working, this change was made, and it stopped. Points out that more tests would be good.

**Comment by duncandewhurst** [comment]
Closed by https://github.com/Open-Telecoms-Data/cove-ofds/pull/103
