### ISSUE TITLE
Download CSV's

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#16]
Should people be able to download all the CSV's for any data pages?

Flattentool already makes them on disk for us, so it's just a case of exposing them in the interface.

See https://github.com/Open-Telecoms-Data/cove-ofds/issues/15 - if they can upload, download makes sense

**Comment by duncandewhurst** [comment]
Yes please!

**Comment by duncandewhurst** [comment]
Looks good on the test server. Can we offer both the individual CSVs and a zip file containing all the CSVs?

That way, users who want to download just one file can do so without needing to unzip the archive, and users who want to download all the files can do so without clicking on each individual file.

![image](https://user-images.githubusercontent.com/19265814/200443450-7202b412-30c9-40c9-a86f-1c1ffdc49fc2.png)

Edit: Please name the compressed file `data.zip`. Thanks!

**Comment by ghost** [comment]
> Can we offer both the individual CSVs and a zip file containing all the CSVs?

On 2022-11-08 branch

**Comment by duncandewhurst** [comment]
Looks good. There's one outstanding change from my previous comment:

> Edit: Please name the compressed file data.zip. Thanks!

**Comment by duncandewhurst** [comment]
> Please name the compressed file data.zip. Thanks!

This is done on live - closing.
