### ISSUE TITLE
Update documentation URLs to point to /latest/

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#34]
Currently, most URLs point to `0.1-dev` because some of the docs have been rearranged for the beta. Once we make a beta release, we should update the URLs to point to `latest`

**Comment by duncandewhurst** [comment]
Beta release PR: https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/181

**Comment by ghost** [comment]
This is URL's in templates, lots of links that point to docs. Some search and replaces in https://github.com/Open-Telecoms-Data/cove-ofds/tree/live/cove_ofds/templates/cove_ofds should do it.

Also, you may want https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/32 to be merged in, a version of the library released and requirements upgraded in this app. That will be needed if there are any changes in the new release of the schema.

**Comment by duncandewhurst** [comment]
> Also, you may want [Open-Telecoms-Data/lib-cove-ofds#32](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/32) to be merged in, a version of the library released and requirements upgraded in this app. That will be needed if there are any changes in the new release of the schema.

Noting that the PR for that issue (https://github.com/Open-Telecoms-Data/lib-cove-ofds/pull/35) is now merged.

There are no schema changes in the `1__0__0__beta` release so for the time being it's in sync with the `0.1-dev` branch. However, we will be making changes on `0.1-dev`, so it would be good to release a new version of the library and upgrade the requirements so that we don't inadvertently break CoVE by making a change to the `0.1-dev` schema.

**Comment by ghost** [comment]
> so that we don't inadvertently break CoVE by making a change to the 0.1-dev schema.

https://github.com/Open-Telecoms-Data/lib-cove-ofds/blob/main/libcoveofds/schema.py#L9

The library is locked to a tag or commit so this won't happen. (I should add a code comment to that affect)

**Comment by duncandewhurst** [comment]
Makes sense. Thanks!

**Comment by ghost** [comment]
Can this now be closed?

**Comment by duncandewhurst** [comment]
Yes :-)
