### ISSUE TITLE
Render words in backticks as code

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#35]
This applies to both JSON Schema validation errors and Python validation errors, so moving to a new issue. 

https://github.com/Open-Telecoms-Data/cove-ofds/pull/32#issuecomment-1309483332

**Comment by codemacabre** [comment]
@odscjames Do we want to keep the backticks within the preformatted code style? i.e. `` `foo` `` or ` foo `? My gut feeling is the latter, but thought I'd check.

**Comment by ghost** [comment]
Question for @duncandewhurst or @lgs85

**Comment by lgs85** [comment]
> Do we want to keep the backticks within the preformatted code style? i.e. `` `foo` `` or `foo`? My gut feeling is the latter, but thought I'd check.

Yes, the latter, so `foo`. Thanks!

**Comment by ghost** [comment]
on live for testing

**Comment by duncandewhurst** [comment]
Looks good! I'll close this issue in favour of the related one I created earlier today:

* https://github.com/Open-Telecoms-Data/cove-ofds/issues/71
