### ISSUE TITLE
prefixItems error title and description

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#37]
Can you do a PR to edit https://github.com/Open-Telecoms-Data/cove-ofds/blob/live/cove_ofds/templates/cove_ofds/jsonschema_validation_panel.html#L3 ? The source spreadsheet was blank

**Comment by duncandewhurst** [comment]
Is a `prefixItems` error ever reported to the user?

The [results](https://ofds.cove.opendataservices.coop/data/48b8f210-2468-4d10-8e3e-7b1390d7acf5) for a file in which the first item in `links` is invalid against the `prefixItems` schema just report the 'child' `const` validation errors.

**Comment by ghost** [comment]
Oh fair enough then :-)
