### ISSUE TITLE
List of possible errors and warning messages

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#4]
Please can we get a list of all the possible error and warning messages that can be displayed to users. I would like to copy-edit them for consistency and clarity.

**Comment by ghost** [comment]
We are trying to move to a situation where the library outputs codes for errors and it's up to the cove app to turn those codes into user facing messages. This is so that other tools can present errors in different ways as they see fit based on different user needs. Thus I'll move this to Cove repository.

**Comment by ghost** [comment]
One big source of these human messages will be https://github.com/Open-Telecoms-Data/cove-ofds/blob/live/cove_ofds/templates/cove_ofds/additional_checks_table.html - currently blank but we can ping you when it's got content and you can edit as much as you want!

**Comment by ghost** [comment]
@duncandewhurst Please edit https://github.com/Open-Telecoms-Data/cove-ofds/blob/live/cove_ofds/templates/cove_ofds/additional_checks_table.html directly

**Comment by duncandewhurst** [comment]
In https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/8#issuecomment-1299492010 I've prepared a spreadsheet with proposed text for each additional check. We can refine them there before updating the template.

**Comment by duncandewhurst** [comment]
@odscjames where can I find the error messages that can appear in the validation errors section?

Also, to review the other text that can appear in the interface, should I just look through the templates?

**Comment by ghost** [comment]
> where can I find the error messages that can appear in the validation errors section?

This unfortunately is not an easy one. You are basically asking to redo all the messages that come out of the JSON Schema validation library. I'll need some time to look at this to A) work out how to generate a list and B) provide a means to easily rewrite them, including thinking about how I18N will be handled in the future.

> Also, to review the other text that can appear in the interface, should I just look through the templates?

Yes

**Comment by duncandewhurst** [comment]
>  You are basically asking to redo all the messages that come out of the JSON Schema validation library. I'll need some time to look at this to A) work out how to generate a list and B) provide a means to easily rewrite them, including thinking about how I18N will be handled in the future.

I think this has all been done already in the OCDS DRT - maybe check with Ben or David R?

**Comment by duncandewhurst** [comment]
I've extracted the error messages from the jsonschema library ([`_validators.py`](https://github.com/python-jsonschema/jsonschema/blob/d715573aa84833fcc360066d31f21f6abdb3cc23/jsonschema/_validators.py#L103) and [`_format.py`](https://github.com/python-jsonschema/jsonschema/blob/6d04fd7041e2cf45836f04858183b453c0b551c3/jsonschema/_format.py#L139)) into a [spreadsheet](https://docs.google.com/spreadsheets/d/1Tc7XQZi8CU_ZfvgnriFQxD4Sv_bM9GGxy54KwBfvaVM/).

For each error message that relates to a keyword/format/type used in the OFDS schema, I've proposed an error title and error description to show in the CoVE validation errors interface proposed in https://github.com/Open-Telecoms-Data/cove-ofds/issues/22. I've also noted which columns should appear in the table for each error type.

In https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/177, I've added an invalid network package that contains a field that fails each keyword/format/type used in the schema.

**Comment by ghost** [comment]
Can this be closed in favour of #22 ?

**Comment by duncandewhurst** [comment]
Yep, I think that the spreadsheet linked in https://github.com/Open-Telecoms-Data/cove-ofds/issues/4#issuecomment-1306380982 is sufficient.
