### ISSUE TITLE
If map given an empty nodes or span files, it crashes

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#43]
To test: merge https://github.com/Open-Telecoms-Data/cove-ofds/pull/42 so you can upload only a node or spans, both not required. Only upload one of the files, leave the other blank. Map has a JS error. "Could not download data or create layer:  Error: Bounds are not valid."

**Comment by Lathrisk** [comment]
~@odscjames Is this fixed elsewhere? I'm not sure I understand the issue.~

**Comment by ghost** [comment]
From commit 6c798c32a0bd2dfb8ddb7194f2359effaee3aa67 

> If a single geojson file is uploaded this will prevent errors and return an console log that one of the files could not be loaded. This is less elegant than switching which layers to create but that route has added complexity. A good future improvement

So do you want to leave this issue open?

**Comment by Lathrisk** [comment]
@odscjames This issue should now be resolved so I think it is safe to close it. The suggested improvement is largely efficiency focused.
