### ISSUE TITLE
Document deletion schedule

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#44]
We should document how long results are available for and how long data is stored for on the landing page. The [OCDS DRT](https://standard.open-contracting.org/review/) has some copy that we can consider reusing.

**Comment by ghost** [comment]
It's currently 7 days but it's a setting which is super easy to change. Just put content in this issue or PR.

**Comment by ghost** [comment]
It's now 90 days
