### ISSUE TITLE
maps: how to visualise when either nodes.geojson or spans.geojson fail to convert (but not both)

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/cove-ofds#45]
Apologies @odscjames @duncandewhurst  if this is duplicated as pushed for time and wanted to log things I'm picking up while demoing.

Looking at [this example](https://ofds.cove.opendataservices.coop/data/3e933979-646e-4452-a73c-98bc42236c18) where one node `type` has been changed to a non-standard entry, I'm getting a greyed out map with non-functioning zoom buttons. Sometimes the span is plotted for me and sometimes not (this might be a function of my browser and poor wifi). It would be good to make sure that we get consistent behaviour in this scenario, which I expect will be a common one.

**Comment by lgs85** [comment]
possible overlap with #6

**Comment by ghost** [comment]
I see from the link the original input was JSON.

> when either nodes.geojson or spans.geojson fail to convert (but not both)

IMO this shouldn't be a situation we deal with - either the JSON->GeoJSON should work and produce both valid nodes & spans files or it should just break.

> how to visualise

https://github.com/Open-Telecoms-Data/cove-ofds/issues/24 is the issue for that.

> where one node type has been changed to a non-standard entry

Logged here https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/39

Also related to https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/27 which we haven't had a lot of time to work on!

>  if this is duplicated as pushed for time

No worries - but if you are happy this is logged elsewhere can we close this one?

**Comment by lgs85** [comment]
Thanks James, all looks good.
