### ISSUE TITLE
413 Request Entity To Large

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#49]
Seen when uploading https://www.itu.int/en/ITU-D/Technology/Pages/OpenFibre.aspx

**Comment by duncandewhurst** [comment]
I got the same error with the OFDS-formatted version of the data shared in [Planio-36509](https://opendataservices.plan.io/issues/36509).

**Comment by ghost** [comment]
That PR fixes things in local docker but on Dokku servers we also need:

    dokku nginx:set openfibrecove-2022-11-18-docker-from-live client-max-body-size 100m

**Comment by duncandewhurst** [comment]
I can upload the Brazil data without any issues so I assume that this issue can be closed.
