### ISSUE TITLE
Add support for uploading XLSX and ODS files (remove file upload text)

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#63]
From @lgs85's discussions with early implementers, we think it would be useful to support spreadsheets as an upload format for CoVE, though not a formal publication format for the standard.

Please add a spreadsheet tab to the data upload interface with the following copy (note the update to the introductory paragraph):

![image](https://user-images.githubusercontent.com/19265814/204706326-ac7ab766-ac7b-416c-9205-523920c5ca76.png)

The spreadsheet tab should appear on the right after the CSV tab. The fact that it replaces the JSON tab in the above screenshot is just an artefact of my use of Firefox's web developer tools to edit the interface.

**Comment by ghost** [comment]
Should there be another new issue - add support for downloading XLSX and ODS as well as CSV?

**Comment by ghost** [comment]
For future ref, if you want me to update content, please copy and paste a string into the issue, not just a screenshot :smile:

**Comment by ghost** [comment]
Ready for testing on live

**Comment by duncandewhurst** [comment]
Tested uploading XLSX and ODS files and it works. One small change for consistency with the other upload forms: please remove the 'File upload' text that appears before the 'Browse' button:

![image](https://user-images.githubusercontent.com/19265814/206294464-2ecd2e84-aae6-4ea0-9517-01ce0236b789.png)

Edit: I've renamed the issue to reflect the outstanding task

**Comment by ghost** [comment]
> One small change for consistency with the other upload forms: please remove the 'File upload' text that appears before the 'Browse' button:

Now on live to test

**Comment by duncandewhurst** [comment]
Looks good. Thanks!
