### ISSUE TITLE
'Non-unique identifiers' heading count wrong

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#64]
From https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/51#issuecomment-1332821598

Whilst testing I noticed that the failure count in the heading is incorrect:

![image](https://user-images.githubusercontent.com/19265814/204922345-691f1346-420a-4967-aadd-a825c2d1465b.png)

Some basic test data for posterity:

```json
{
  "networks": [
    {
      "id": "31d17f87-c931-4b69-9341-5e3f1a095000",
      "nodes": [
        {
          "id": "1"
        },
        {
          "id": "1"
        },
        {
          "id": "1"
        }
      ]
    }
  ]
}
```

**Comment by ghost** [comment]
Ready to test on live

**Comment by duncandewhurst** [comment]
Looks good!
