### ISSUE TITLE
Add support for downloading XLSX and ODS files (update filenames)

### ISSUE THREAD

**Issue by lgs85** [Open-Telecoms-Data/cove-ofds#67]
Following #63, it would also be useful to support XLSX and ODS as download formats for OFDS CoVE

**Comment by ghost** [comment]
Ready for testing on live

**Comment by duncandewhurst** [comment]
Looks good! I noticed an issue with the ODS file, which I've logged against Flatten Tool:

* https://github.com/OpenDataServices/flatten-tool/issues/414

A couple of minor changes:

- ODS format
  - [x] Set `-o data.ods` in Flatten Tool
  - [ ] Change the download link label to `data.ods (<filesize>)`, e.g. ![image](https://user-images.githubusercontent.com/19265814/206295684-245b1bb4-3d40-409a-8911-0bf0b63e9e8c.png)
- XLSX format
  - [x] Set `-o data.xlsx` in Flatten Tool
  - [x] Change the download link label to `data.xlsx (<filesize>)`, e.g. ![image](https://user-images.githubusercontent.com/19265814/206295857-3848ea57-67f1-4b53-92ab-b39e831c174c.png)

Edit: I've updated the issue title to reflect the outstanding tasks.

**Comment by ghost** [comment]
All ready for testing on live

**Comment by duncandewhurst** [comment]
Looks good. Thanks!
