### ISSUE TITLE
Show JSON Schema validation errors with id of the node or span, not just JSON path

### ISSUE THREAD

**Issue by ghost** [Open-Telecoms-Data/cove-ofds#7]

**Comment by duncandewhurst** [comment]
It's actually the id of the node or link that we're interested in, since we expect most publishers to publish a single network with many nodes and links, rather than many networks.

**Comment by ghost** [comment]
Ready to review

**Comment by duncandewhurst** [comment]
Looks like this is working well but the layout of the feedback to users could be improved. See my suggestions in https://github.com/Open-Telecoms-Data/cove-ofds/issues/22

**Comment by ghost** [comment]
Closing then, will work in other ticket
