### ISSUE TITLE
Network.id erroneously reported as missing

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#70]
Test data:

```json
{"networks": [{"id": "1"}]}
```

[CoVE results](https://ofds.cove.opendataservices.coop/data/16ad043c-8818-4166-90d9-29f3340b555f)

**Comment by ghost** [comment]
Also, erroneously reports links as missing:

    {"networks": [{"links": [] }]}

I have a theory ....

**Comment by ghost** [comment]
https://github.com/python-jsonschema/jsonschema/issues/1030 is my preferred fix - we can do some string manipulation to get the error in the meantime.

**Comment by ghost** [comment]
Now on live to test

**Comment by duncandewhurst** [comment]
Looks good!
