### ISSUE TITLE
Render code-formatted links differently from code-formatted text

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#71]
For example, `Geometry.type` is a link, but a user wouldn't know that unless they hovered over it:

![image](https://user-images.githubusercontent.com/19265814/206287761-d9f91b3f-f5f6-4a3b-95af-b5a8c9c64294.png)

GitHub renders [`code-formatted links`](www.example.com) differently from `code-formatted text`.

**Comment by ghost** [comment]
Ready for testing on live

**Comment by duncandewhurst** [comment]
Looks good. Thanks!
