### ISSUE TITLE
GeoJSON: Update CoVE to rely on the featureType field rather than which file is uploaded in which box

### ISSUE THREAD

**Issue by duncandewhurst** [Open-Telecoms-Data/cove-ofds#96]
In https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/266, we added a `featureType` field to the GeoJSON publication format to distinguish between nodes and spans and to support publication as a single file.

The task is to update CoVE to rely on the new field rather than which file is uploaded in which box in the GeoJSON upload interface.

The background to the change is discussed in https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/207.

The revised documentation is available at https://open-fibre-data-standard.readthedocs.io/en/0.3-dev/reference/publication_formats/geojson.html.

**Comment by ghost** [comment]
Think can now close, this is live
